{
  "name": "travelxpress-website",
  "version": "1.0.0",
  "description": "Serverless function for TravelXpress website",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-fetch": "^2.6.7"
  }
}

